### ISSUE TITLE
Need filter on Leave history page.

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/intranet#82] opened 2015-10-27 07:01 UTC
Present leave history page lists all leaves taken so far. 
Need filter 
- On name
- On date - Given a date should display list of all employees who are on leave on that day.

By default show current year leave and add option at top to select previous year to list leaves taken during that year. In this case year will be calendar year and NOT financial year.

**Comment by Shwetakale** [comment] 2018-07-09 05:59
Duplicate of https://github.com/joshsoftware/intranet/issues/117

**Closed by Shwetakale** 2018-07-09 05:59 UTC
